name: Aufgabe 1 - Docker Deploy

on: push

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5

            - name: SSH setup
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/meinKey.pem
                  chmod 400 ~/.ssh/meinKey.pem
                  ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

            - name: Copy project files to EC2
              run: scp -i ~/.ssh/meinKey.pem -r ./frontend ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/frontend

            - name: Build and Run Docker on EC2
              run: ssh -i ~/.ssh/meinKey.pem ubuntu@${{ secrets.EC2_IP }} "
                sudo docker build -t frontend-image /home/ubuntu/frontend &&
                sudo docker stop mein-frontend-container || true &&
                sudo docker rm mein-frontend-container || true &&
                sudo docker run -d --name mein-frontend-container -p 8081:80 frontend-image
                "