name: Restart Web

on:
  workflow_dispatch: 

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: SSH setup
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/meinKey.pem
          chmod 400 ~/.ssh/meinKey.pem
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

      - name: Restart Docker container on EC2
        run: ssh -i ~/.ssh/meinKey.pem ubuntu@${{ secrets.EC2_IP }} "
          sudo docker stop mein-frontend-container || true &&
          sudo docker rm mein-frontend-container || true &&
          sudo docker run -d --name mein-frontend-container -p 8081:80 frontend-image
          "